export { Register } from './register'
export { RecoverPassword } from './recoverPassword'
export { RecoverPasswordFinish } from './recoverPasswordFinish'
export { Login } from './login'
export { DashboardAdotador  } from './dashboardAdotador'
export { Loading } from './loading'
export { EditarCachorro } from './editarCachorro'